name: amlr-gliders
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9 #conflict error for glidertools if using 3.10
  - glidertools
  - google-crc32c=1.1
  - google-cloud-secret-manager=2.12
  - ipdb
  - pyarrow
  - spyder

  # packages for glidertools
  # - pykrige
  # - plotly

  # packages for gdm
  # - gsw #and for glidertools
  # - netcdf4
  # - numpy
  # - pandas
  # - scipy
  # - shapely
  # - xarray
  # - pyyaml

  - pip
  - pip:
    - -e git+https://github.com/smwoodman/gdm.git#egg=gdm
    # - -e amlr-gliders
