name: amlr-gliders
channels:
  - conda-forge
  - default
dependencies:
  - python
  - pip
  
  # Misc
  - ipdb
  - ipykernel

  # Used in amlr-gliders scripts
  - google-crc32c=1.1.0
  - google-cloud-secret-manager=2.12.0
  - pyarrow>=9.0

  # packages for glidertools
  - glidertools
  - pykrige
  - plotly
  - cmocean

  # packages for gdm, list here to install through conda
  - gsw
  - netcdf4
  - numpy
  - pandas
  - scipy
  - shapely
  - xarray
  - pyyaml

  # # From GliderTools/setup.cfg
  # - numexpr
  #   # netcdf4
  #   # pandas
  #   # xarray
  #   # numpy
  # - scikit-learn
  #   # scipy
  # - tqdm
  # - matplotlib
  #   # gsw

  # - pip:
  #   - -e git+https://github.com/smwoodman/gdm.git#egg=gdm
  #   # - -e git+https://github.com/kerfoot/gdm.git#egg=gdm
  #   - -e git+https://github.com/us-amlr/amlr-gliders.git#egg=amlr_gliders
