name: amlr-gliders
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - glidertools
  - google-crc32c=1.1
  - google-cloud-secret-manager=2.12
  - ipdb=13
  - pip
  - pyarrow=9.0
  # - spyder

  # packages for glidertools
  # - pykrige
  # - plotly

  # packages for gdm
  # - gsw #and for glidertools
  # - netcdf4
  # - numpy
  # - pandas
  # - scipy
  # - shapely
  # - xarray
  # - yaml
