name: amlr-gliders
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - argparse
  - arrow=1.2
  - gsw=3.4
  - ipykernel=6.13
  - ipython=7.31
  - jupyterlab
  - netcdf4=1.5
  - numpy=1.22
  - pandas=1.4
  - pip=21.3
  - pyarrow=7.0
  - pyyaml=6.0
  - scipy=1.7
  - shapely=1.8
  - spyder=5.3
  - xarray=0.20
  - yaml=0.2
