name: amlr-gliders
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - glidertools
  - google-crc32c
  - google-cloud-secret-manager
  - ipdb
  - pip
  - pyarrow
  # - spyder

  # packages for glidertools
  # - pykrige
  # - plotly

  # packages for gdm
  # - gsw #and for glidertools
  # - netcdf4
  # - numpy
  # - pandas
  # - scipy
  - shapely
  # - xarray
  - yaml
