name: amlr-gdm
channels:
  - default
  - conda-forge
dependencies:
  - arrow=1.2.2
  - gsw
  - ipykernel=6.13.0
  - ipython=7.31.1
  - netcdf4
  - numpy=1.22.*
  - pandas=1.4.*
  - pip=21.3
  - pyarrow=7.0.0
  - python=3.8.*
  - shapely=1.8.*
  - xarray=0.20.*
