name: amlr-gliders
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - pip
  
  # Misc
  - ipdb
  - ipykernel

  # Used in amlr-gliders scripts
  - dask=2023.4
  - google-crc32c=1.1.0
  - google-cloud-secret-manager=2.12.0
  - pyarrow=9.0

  # # packages for glidertools
  # - glidertools
  # - pykrige
  # - plotly
  # - cmocean

  # packages for gdm, list here to install through conda
  - gsw=3.6 #and for glidertools
  - netcdf4=1.6
  - numpy=1.24
  - pandas=2.0
  - scipy=1.10
  - shapely=2.0
  - xarray=2023.4
  - pyyaml=6.0

  - pip:
    - -e git+https://github.com/smwoodman/gdm.git#egg=gdm
    - -e git+https://github.com/us-amlr/amlr-gliders.git#egg=amlr_gliders
